added routes for job list & job details
p5chi-auf/PentaBee-api pull request #10
Opened 2019-05-20 13:17 UTC by nspc97

Unfortunately, we don't know why but the changes from the last pull request (added fixtures) are also displayed in the new pull request, but we have also added the new changes with routes for jobs_list (/api/activities) and for job details (/api/activities/{id})

2019-05-21 12:43 UTC, SpartakusMd requested changes

2019-05-21 12:43 UTC, SpartakusMd commented on src/Entity/Technology.php
> +     * @Groups({"ActivityDetails"})
Why have you made only this field available in the ActivityDetails? What about the others?

2019-05-21 12:43 UTC, SpartakusMd commented on src/Entity/Type.php
> +     * @Groups({"ActivityDetails"})
Why have you made only this field available in the ActivityDetails? What about the others?

2019-05-21 12:43 UTC, SpartakusMd commented on src/Entity/User.php
> +     * @Groups({"ActivityDetails"})
Why have you made only this field available in the ActivityDetails? What about the others?

2019-05-21 12:43 UTC, SpartakusMd commented on templates/api/activity.html.twig
> +{# templates/api/activities.html.twig #}
Please remove this file or ignore it.

2019-05-22 08:11 UTC, SpartakusMd requested changes

2019-05-22 08:11 UTC, SpartakusMd commented on composer.json
> +    "knpuniversity/oauth2-client-bundle": "^1.28",
You should not have changes from two tasks on the same brach.

2019-05-22 08:33 UTC, SpartakusMd commented
Please be specific about the comments. Don't use the same comment twice. Describe the changes.

2019-05-22 08:48 UTC, nspc97 commented on composer.json
> +    "knpuniversity/oauth2-client-bundle": "^1.28",
@SpartakusMd 
 Jms/serializer is used for the task with job details/list, so it's related to this task.
But in the case of oauth2 bundle...we need to simply remove this row, or we can just ignore it for this pull request?

2019-05-22 12:32 UTC, SpartakusMd commented on composer.json
> +    "knpuniversity/oauth2-client-bundle": "^1.28",
By the way, nelmio/api-doc-bundle is also from another task :)

2019-05-22 12:33 UTC, merged