[BE] Edit job
p5chi-auf/PentaBee-api pull request #20
Opened 2019-06-06 08:03 UTC by MihaiDruta

[BE] Edit job
https://trello.com/c/Cb1o51VT/12-be-edit-job

Added necessary functions for editing an activity.

2019-06-06 08:04 UTC, nspc97 approved these changes

2019-06-06 08:59 UTC, SpartakusMd requested changes

2019-06-06 08:59 UTC, SpartakusMd commented on src/Controller/ActivityController.php
> +        $manager->persist($activityToEdit);
Implement a save method in the repository instead of this.

2019-06-06 08:59 UTC, SpartakusMd commented on src/Entity/Activity.php
> +    public function getTechnologies()
Add return type + DocBlock (comment)

2019-06-06 08:59 UTC, SpartakusMd commented on src/Entity/Activity.php
> +    public function getTypes()
Add return type + DocBlock (comment)

2019-06-06 08:59 UTC, SpartakusMd commented on src/Service/ActivityTransformer.php
>      ): Activity {
This method has become too big. Please separate into multiple private methods.

2019-06-06 08:59 UTC, SpartakusMd commented on src/Controller/ActivityController.php
> +            return new Response($errorsString);
Maybe JsonResponse with the status code 400?

2019-06-10 06:48 UTC, SpartakusMd approved these changes

2019-06-10 06:48 UTC, merged