[BE] Password update
p5chi-auf/PentaBee-api pull request #24
Opened 2019-06-11 11:39 UTC by nspc97

[BE] Password update
https://trello.com/c/fIH8X2Hw/41-be-password-update

Changed register and user_update logic.

2019-06-11 11:45 UTC, MihaiDruta approved these changes

2019-06-11 13:59 UTC, SpartakusMd requested changes

2019-06-11 13:59 UTC, SpartakusMd commented on src/Controller/UserController.php
>          $data = $request->getContent();
We forgot to add a check that you can edit only your profile. Please compare the logged in user with the user which is being edited.

2019-06-11 13:59 UTC, SpartakusMd commented on src/Controller/UserController.php
> +        $data = $request->getContent();
Add a check that you can change only your password. Please compare the logged in user with the user which is being edited.

2019-06-11 13:59 UTC, SpartakusMd commented on src/DTO/UserDTO.php
> +    public $confirmNewPassword;
You can rename the fields so you don't have 2 confirm fields. On register you would have password, confirmPassword and on password change you would have oldPassword, password, confirmPassword. The validation rules will also be simpler in this case.

2019-06-11 13:59 UTC, SpartakusMd commented on src/Exceptions/NotValidOldPassword.php
> +}
Add new lines at the end of files.

2019-06-11 13:59 UTC, SpartakusMd commented on src/Service/UserTransformer.php
> +}
New line.

2019-06-11 13:59 UTC, SpartakusMd commented on src/Service/UserTransformer.php
> +        $entity = $this->userRepo->find($dto->id);
On change password you should have only the passwords in the requests. The user id is sent in URL. Pass the $user object when calling `changePasswordTransform()`

2019-06-12 12:09 UTC, MihaiDruta commented on src/Controller/RegisterController.php
>          $userDTO = $serializer->deserialize(
Inject the serializer in `__construct()` method like `validator` and `transformer`

2019-06-13 08:50 UTC, SpartakusMd requested changes

2019-06-13 08:50 UTC, SpartakusMd commented on src/Controller/UserController.php
> +    public function editUser($id, Request $request, UserRepository $userRepository, UserInterface $user)
I would use `$currentUser` or `$loggedUser` or `$authenticatedUser` as it better reflects what kind of user is this.

2019-06-13 08:50 UTC, SpartakusMd commented on src/Controller/UserController.php
> +        $userPage = $userRepository->find($id);
This is a user, not a page. Use `$user` or `$affectedUser`.

2019-06-13 08:50 UTC, SpartakusMd commented on src/Controller/UserController.php
> +        if ($userUsername === $userPage) {
Compare user ids, not usernames ..

2019-06-13 08:50 UTC, SpartakusMd commented on src/Controller/UserController.php
> +        if ($userUsername === $userPage) {
It should be the reverse. If the ids (or usernames in your case) don't match, return the error JSON, as so, you won't have too much identation and you should alway fail / return fast from the functions.

2019-06-13 08:50 UTC, SpartakusMd commented on src/Controller/UserController.php
> +        UserInterface $user
Same here, rename `$user`

2019-06-13 08:50 UTC, SpartakusMd commented on src/Service/UserTransformer.php
> +        $id
Send the User object, not the id. You already searched the user in the database, there's no reason to do it twice.

2019-06-13 08:50 UTC, SpartakusMd commented on src/Service/UserTransformer.php
> +        $id
Send the User object, not the id. You already searched the user in the database, there's no reason to do it twice.

2019-06-14 09:28 UTC, SpartakusMd approved these changes

2019-06-14 09:28 UTC, SpartakusMd commented on src/Controller/UserController.php
> +            return new JsonResponse(['message' => 'Access denied!'], Response::HTTP_BAD_REQUEST);
Actualy it should be `Response::HTTP_FORBIDDEN` as the current user cannot edit this user. You can fix it after the merge.

2019-06-14 09:28 UTC, SpartakusMd commented on src/Controller/UserController.php
> +            return new JsonResponse(['message' => 'Access denied!'], Response::HTTP_BAD_REQUEST);
Actualy it should be Response::HTTP_FORBIDDEN as the current user cannot edit this user. You can fix it after the merge.

2019-06-14 09:28 UTC, SpartakusMd commented on src/Controller/UserController.php
> +            $data = $request->getContent();
Indentation is wrong in this method :)

2019-06-14 09:28 UTC, SpartakusMd commented on src/Exceptions/NotValidOldPassword.php
> +    public function __construct(string $message = '')
Remove the construct if it doesn't do anything.

2019-06-14 09:28 UTC, merged