[BE] Apply for a job
p5chi-auf/PentaBee-api pull request #36
Opened 2019-06-19 13:05 UTC by nspc97

[BE] Apply for a job
https://trello.com/c/E1dTAfCz/50-be-apply-for-a-job

2019-06-19 13:06 UTC, MihaiDruta approved these changes

2019-06-19 13:26 UTC, SpartakusMd requested changes

2019-06-19 13:26 UTC, SpartakusMd commented on src/Repository/ActivityUserRepository.php
> +        $manager->persist($activityUser);
Add the method `save()` to the repository and use it here.

2019-06-19 13:26 UTC, SpartakusMd commented on src/Repository/ActivityUserRepository.php
> +        $activityUser->setType(1);
Use the constant from `ActivityUser` instead of number.

2019-06-19 13:26 UTC, SpartakusMd commented on src/Controller/ActivityController.php
> +        $repo->apply($activity, $applierUser);
Before `apply()` check if user has already applied. He can't apply twice to the same activity.

2019-06-19 13:26 UTC, SpartakusMd commented on src/Controller/ActivityController.php
> +        $repo->apply($activity, $applierUser);
Also check status and deadline.

2019-06-21 13:26 UTC, SpartakusMd approved these changes

2019-06-21 13:27 UTC, SpartakusMd commented on src/Controller/ActivityController.php
> +     *     description="Already applied/ activity finnished/ deadline passed!",
For each distinct error you should have a separate `@SWG\Response` block.

2019-06-21 13:27 UTC, merged