[BE] Validate an user for a job by job owner
p5chi-auf/PentaBee-api pull request #40
Opened 2019-06-25 07:40 UTC by nspc97

[BE] Validate an user for a job by job owner
https://trello.com/c/Ik5lwLAp/60-be-validate-an-user-for-a-job-by-job-owner

2019-06-25 07:43 UTC, MihaiDruta requested changes

2019-06-25 07:43 UTC, MihaiDruta commented on src/Controller/ActivityController.php
> +     *     @SWG\Property(property="message", type="string", example="User invited with succes!"),
Wrong message. Should be "User assigned with succes!".

2019-06-25 07:43 UTC, MihaiDruta commented on src/Controller/ActivityController.php
> +            return new JsonResponse(['message' => 'User cannot be assigned!'], Response::HTTP_OK);
Wrong response code. Should be probably 400.

2019-06-25 07:45 UTC, MihaiDruta approved these changes

2019-06-26 06:40 UTC, SpartakusMd requested changes

2019-06-26 06:40 UTC, SpartakusMd commented on src/Controller/ActivityController.php
> +        $activityUserRepo->assign($userApplier);
Method is redundant. Add it's contents here and remove it.

2019-06-26 06:53 UTC, SpartakusMd approved these changes

2019-06-26 06:53 UTC, merged