[BE] Add filter & sortings for the list of jobs
p5chi-auf/PentaBee-api pull request #52
Opened 2019-07-04 07:13 UTC by MihaiDruta

[BE] Add filter & sortings for the list of jobs
https://trello.com/c/T12F817f/52-be-add-filter-sortings-for-the-list-of-jobs

Adding filters and sorting for activity list.

2019-07-04 07:17 UTC, nspc97 approved these changes

2019-07-04 11:50 UTC, SpartakusMd requested changes

2019-07-04 11:50 UTC, SpartakusMd commented on src/Filters/ActivityListFilter.php
> +            if (array_key_exists('name', $filter)) {
Use `if (!empty('name', $filter))`. Because one could send empty parameters.

2019-07-04 11:50 UTC, SpartakusMd commented on src/Filters/ActivityListFilter.php
> +    public function setFilterFields($filter)
Parameter typehint and method return typehint.

2019-07-04 11:50 UTC, SpartakusMd commented on src/Filters/ActivityListFilter.php
> +                $this->owner = $this->userRepository->find($filter['owner']);
Store the id, don't search it in the database. In the query builder you will do the search.

2019-07-04 11:50 UTC, SpartakusMd commented on src/Filters/ActivityListFilter.php
> +                $this->assignedUser = $this->userRepository->find($filter['assignedUser']);
Store the id, don't search it in the database.

2019-07-04 11:50 UTC, SpartakusMd commented on src/Filters/ActivityListSort.php
> +            if (array_key_exists('name', $sorting)) {
Use if (!empty('name', $filter)). Because one could send empty parameters.

2019-07-04 11:50 UTC, SpartakusMd commented on src/Filters/ActivityListSort.php
> +                $this->name = $sorting['name'];
Validate what value is coming here. What if someone make a request `?sortby[name]=invalid_value` ?

2019-07-04 11:50 UTC, SpartakusMd commented on src/Filters/ActivityListFilter.php
> +                $this->status = $filter['status'];
Make sure status is integer.

2019-07-04 11:50 UTC, SpartakusMd commented on src/Repository/ActivityRepository.php
>              ->where('activity.public = 1')
For these 3 `where/orWhere` you should be using https://www.doctrine-project.org/api/orm/latest/Doctrine/ORM/Query/Expr/Orx.html in order to exclude collision with the next conditions.

2019-07-05 06:27 UTC, nspc97 approved these changes

2019-07-05 13:41 UTC, SpartakusMd approved these changes

2019-07-05 13:41 UTC, SpartakusMd commented on src/Filters/ActivityListPagination.php
> +            $this->currentPage = 1;
FYI, if you declare the field with a default value `public $currentPage = 1;` you won't need the `else` branch ))

2019-07-08 07:35 UTC, merged