[BE] Add location to user profile
p5chi-auf/PentaBee-api pull request #67
Opened 2019-07-24 13:36 UTC by nspc97

[BE] Add location to user profile
https://trello.com/c/AxyjrC0N/83-be-add-location-to-user-profile

2019-07-24 15:07 UTC, MihaiDruta approved these changes

2019-07-25 08:36 UTC, SpartakusMd requested changes

2019-07-25 08:36 UTC, SpartakusMd commented on src/DTO/UserDTO.php
> +     * @Assert\Choice(choices = {"CHI","NYC","BOS","FRA","PAR","ORL","BUC","BRA","CLU","IAS","HAN","GUA","LYO"},
Please use Assert/Callback to validate this field. Create a constant in the User class with the list of available locations and use it for validation, documentation & fixtures.

2019-07-26 13:11 UTC, SpartakusMd approved these changes

2019-07-26 13:11 UTC, merged