[BE] Upload activity cover image
p5chi-auf/PentaBee-api pull request #72
Opened 2019-07-30 15:05 UTC by MihaiDruta

[BE] Upload activity cover image
https://trello.com/c/dMG8DN4K/82-be-upload-activity-cover-image

1.Added possibility to add a cover to activity
2.The cover is center cropped to a square and resized to all necessary dimensions (all dimensions are stored in services.yaml)
3.Added possibility to remove activity cover
4.Created specific documentation model for activity cover
5.Minor changes to functions related to User Avatar (DELETE request instead of POST for removing avatar, changed model name)

2019-08-02 12:36 UTC, SpartakusMd commented on config/packages/nelmio_api_doc.yaml
> +        description: UserAvatar
Use a descriptive message to be clear about the usage.  Same for ImageActivity.

2019-08-02 12:36 UTC, SpartakusMd commented on src/Controller/UserController.php
> +     * * @SWG\Delete(
Remove a `*` symbol.

2019-08-02 12:37 UTC, SpartakusMd requested changes

2019-08-02 12:37 UTC, SpartakusMd commented on src/Service/ImageManager.php
> +    private function initializeSizeDirectory($entity): void
Something's fishy here :) we should discuss.

2019-08-05 12:44 UTC, SpartakusMd requested changes

2019-08-05 12:44 UTC, SpartakusMd commented on src/Service/ImageManager.php
> +        //$filename = $targetEntity->getId() . '.' . $uploadedFile->guessExtension();
Don't leave code comented. Remove it.

2019-08-05 12:44 UTC, SpartakusMd commented on src/Service/ActivityCoverManager.php
> +        $this->initializeSizeDirectory($activityCoverDirectory, $activityCoverSize);
You don't need this method. Do everything in the constructor from ImageManager.

2019-08-05 12:58 UTC, nspc97 approved these changes

2019-08-05 13:01 UTC, SpartakusMd approved these changes

2019-08-05 13:23 UTC, merged