[BE] Admin rights
p5chi-auf/PentaBee-api pull request #76
Opened 2019-08-06 12:20 UTC by nspc97

[BE] Admin rights
https://trello.com/c/5vF8vxMG/87-be-admin-rights

2019-08-06 13:41 UTC, MihaiDruta approved these changes

2019-08-06 13:53 UTC, SpartakusMd requested changes

2019-08-06 13:53 UTC, SpartakusMd commented on src/Controller/ActivityController.php
> +        if ($rights === false && $user->getRoles() !== array('ROLE_ADMIN')) {
Use `$this->isGranted('ROLE_ADMIN');`

2019-08-06 13:56 UTC, SpartakusMd commented on src/Controller/ActivityController.php
> +        if ($rights === false && $user->getRoles() !== array('ROLE_ADMIN')) {
Outside of controllers use `Symfony\Component\Security\Core\Authorization\AuthorizationCheckerInterface::isGranted()`

2019-08-07 07:19 UTC, SpartakusMd requested changes

2019-08-07 07:19 UTC, SpartakusMd commented on src/Controller/ActivityController.php
> +        if ($hasAccess && $activity->isPublic() === false) {
Should be `if (!$hasAccess`

2019-08-07 07:19 UTC, SpartakusMd commented on src/Entity/User.php
> +     * @ORM\Column(type="string")
You can't save an array as string in database, use `@ORM\Column(type="json")`

2019-08-07 07:19 UTC, SpartakusMd commented on src/Entity/User.php
> +    public function setRoles(string $roles): void
`$roles` is an array, not string.

2019-08-07 09:15 UTC, SpartakusMd approved these changes

2019-08-07 09:15 UTC, merged