[BE] Fix bugs
p5chi-auf/PentaBee-api pull request #80
Opened 2019-08-08 11:19 UTC by MihaiDruta

[BE] Fix bugs
https://trello.com/c/NPEi8KKJ/95-be-fix-bugs

Fixed bugs:
Feedback:
- User is now able to give feedback only once to a specific user involved on an activity
Pagination:
- If the page is negative a HttpNotFoundException is thrown
- If the page exceeds the maximum number of pages available a HttpNotFoundException is thrown

2019-08-08 11:34 UTC, SpartakusMd requested changes

2019-08-08 11:34 UTC, SpartakusMd commented on src/Filters/PaginatorPageFieldValidator.php
> +class PaginatorPageFieldValidator
Maybe rename class to `PaginatorValidator` and the method to `isPageNumberValid`?

2019-08-08 11:34 UTC, SpartakusMd commented on src/Repository/FeedbackRepository.php
> +    public function canUserGiveFeedback(Activity $activity, User $userFrom, User $userTo): bool
This method doesn't implement all the checks necessary, so it's name should be changed to `hasUserGivenFeedback()`

2019-08-08 11:34 UTC, SpartakusMd commented on src/Handlers/UserHandler.php
> +        }
The block `$context = ...` and `$json = $this->serializer...` should be after this validation. Check all the controllers.

2019-08-08 11:34 UTC, SpartakusMd commented on src/Handlers/UserHandler.php
>              $userListPagination->pageSize = $numResults;
Add this feature to all the paginated lists.

2019-08-08 12:12 UTC, nspc97 approved these changes

2019-08-08 13:00 UTC, SpartakusMd requested changes

2019-08-08 13:00 UTC, SpartakusMd commented on src/Repository/ActivityRepository.php
> +        if ($activityListPagination->pageSize === -1) {
We can't have anymore `pageSize = -1` as we have `PaginatorValidator` :) Check all repozitories.

2019-08-12 06:48 UTC, SpartakusMd approved these changes

2019-08-12 06:49 UTC, SpartakusMd commented
@MihaiDruta please fix conflicts.

2019-08-12 13:51 UTC, merged