[BE] Project manager role
p5chi-auf/PentaBee-api pull request #82
Opened 2019-08-12 11:56 UTC by nspc97

[BE] Project manager role
https://trello.com/c/mY9KaA6l/99-be-project-manager-role

- Each user should get a PM assigned (not mandatory).
- Admins can assign a PM to the user.
- When the PM account is deleted/deactivated, all the users of this PM get unassigned from him.

2019-08-12 12:15 UTC, MihaiDruta requested changes

2019-08-12 12:15 UTC, MihaiDruta commented on src/Controller/UserController.php
> +     * @Rest\Post("/{userId}/set_pm/{pmId}", requirements={"id"="\d+"})
Requirements are not correct

2019-08-12 12:15 UTC, MihaiDruta commented on src/Controller/UserController.php
> +     *     @SWG\Property(property="message", type="string"),
You can add an example message for this response

2019-08-12 12:15 UTC, MihaiDruta commented on src/Entity/User.php
> +     * Comment id linked to.
Wrong description

2019-08-12 12:17 UTC, MihaiDruta approved these changes

2019-08-13 09:02 UTC, SpartakusMd requested changes

2019-08-13 09:02 UTC, SpartakusMd commented on src/Repository/UserRepository.php
> +        $this->clearProjectManager($user);
Rename to `unassignProjectManager`

2019-08-13 09:02 UTC, SpartakusMd commented on src/Controller/UserController.php
> +     * @Rest\Post("/{userId}/set_pm/{pmId}", requirements={"userId"="\d+", "pmId"="\d+"})
Rename `set_pm` to `assign-project-manager`. The ID of PM should be present in the body not in the URL.

2019-08-13 09:02 UTC, SpartakusMd commented on src/Controller/UserController.php
> +     * @Rest\Post("/{id}/set_pm", requirements={"id"="\d+"})
Role management should be general. Only admins can assign roles. An admin can promote anyone to PM or to admin and also demote to PM, user.

2019-08-13 11:31 UTC, SpartakusMd requested changes

2019-08-13 11:31 UTC, SpartakusMd commented on src/Controller/UserController.php
> +     * @Rest\Post("/{id}/set_role", requirements={"id"="\d+"})
In URLs dash "-" should be used instead of underscore "_".

2019-08-13 11:31 UTC, SpartakusMd commented on src/Controller/UserController.php
> +     * @Rest\Post("/{id}/assign_project_manager", requirements={"id"="\d+"})
In URLs dash "-" should be used instead of underscore "_".

2019-08-13 11:31 UTC, SpartakusMd commented on src/DTO/UserDTO.php
> +     * @Serializer\Type("string")
A user can have multiple roles.

2019-08-13 11:31 UTC, SpartakusMd commented on src/DTO/UserDTO.php
> +            $context->addViolation('Please enter a valid ROLE!', array());
The field for which this violation is, was not specified.

2019-08-13 11:31 UTC, SpartakusMd commented on src/Controller/UserController.php
> +        $context = DeserializationContext::create()->setGroups(array('SetRole'));
Why is the group called `SetRole`?

2019-08-13 11:31 UTC, SpartakusMd commented on src/Controller/UserController.php
>          if ($projectManager->getRoles() === array('ROLE_USER')) {
This isn't how you validate if a user has a specific role. Also, you should check specificaly for ROLE_PM as there could be roles like DEV, QA and others.

2019-08-13 11:31 UTC, SpartakusMd commented on src/Controller/UserController.php
> +                    'message' => 'This user in not a PM!'
The message is bad. It says that the user to be changed is not a PM, not that the current user is not a PM.

2019-08-13 11:31 UTC, SpartakusMd commented on src/Controller/UserController.php
> +                    'message' => 'Not found!'
What is not found?

2019-08-14 11:15 UTC, SpartakusMd requested changes

2019-08-14 11:15 UTC, SpartakusMd commented on src/Controller/UserController.php
> +        if ($projectManagerRole !== array('ROLE_PM') || $projectManagerRole !== array('ROLE_ADMIN')) {
You should be using a specific Symfony function to check the role. As ROLE_ADMIN ha already ROLE_PM you won't have to specify it.

2019-08-15 13:37 UTC, merged