[BE] Preparing environment for tests
p5chi-auf/PentaBee-api pull request #83
Opened 2019-08-13 12:01 UTC by MihaiDruta

[BE] Preparing environment for tests
https://trello.com/c/Hz9GcyOy/93-be-preparing-environment-for-tests

1.Configured new SQLite database for tests
2.First functional test on successful registering

2019-08-13 12:03 UTC, nspc97 approved these changes

2019-08-13 13:47 UTC, SpartakusMd requested changes

2019-08-13 13:47 UTC, SpartakusMd commented on config/packages/test/framework.yaml
> +liip_functional_test: ~
Move this to a separate yaml file.

2019-08-13 13:47 UTC, SpartakusMd commented on tests/RegisterTest.php
> +        $this->assertEquals(200, $client->getResponse()->getStatusCode());
Check that the data in the database is present and is correct.

2019-08-14 14:24 UTC, SpartakusMd requested changes

2019-08-14 14:24 UTC, SpartakusMd commented on tests/RegisterTest.php
> +            'email' => 'testemail@test.mail',
Search only by username as it is unique.

2019-08-14 14:24 UTC, SpartakusMd commented on tests/RegisterTest.php
> +        $users = $repository->findBy(array(
Why 2 queries? Use only the second one with only username as search parameter.

2019-08-15 07:16 UTC, merged