[BE] Tests cases for register
p5chi-auf/PentaBee-api pull request #85
Opened 2019-08-15 08:51 UTC by MihaiDruta

[BE] Tests cases for register
https://trello.com/c/wLyKJm1L/106-be-tests-cases-for-register

Test cases for user register

2019-08-15 09:02 UTC, SpartakusMd commented on tests/RegisterTest.php
> +        $data['password'] = 'Test_8';
Read about Data Providers https://phpunit.de/manual/3.7/en/writing-tests-for-phpunit.html

2019-08-16 06:05 UTC, nspc97 approved these changes

2019-08-19 07:05 UTC, SpartakusMd requested changes

2019-08-19 07:05 UTC, SpartakusMd commented on tests/RegisterTest.php
> +    public function testUnsuccessfulRegisterDuplicateUsernameEmail(
Merge together all unsuccessful functions:

- testUnsuccessfulRegisterDuplicateUsernameEmail
- testUnsuccessfulRegisterInvalidUsername
- testUnsuccessfulRegisterInvalidPassword
- testUnsuccessfulRegisterInvalidEmail
- testUnsuccessfulRegisterEmptyNameSurname

2019-08-21 08:59 UTC, merged