Job validation
p5chi-auf/PentaBee-api pull request #86
Opened 2019-08-19 12:20 UTC by nspc97

https://trello.com/c/stFxfgZr/100-be-jobs-for-validation-list

2019-08-19 12:25 UTC, MihaiDruta approved these changes

2019-08-19 16:46 UTC, SpartakusMd requested changes

2019-08-19 16:46 UTC, SpartakusMd commented on src/Controller/ActivityController.php
> +            ($activity->getStatus() === Activity::STATUS_IN_VALIDATION &&
A PM has always access to the jobs posted by users for whom they are a PM. Also here you don't check that the current user is a PM of the owner. Also you have remove admin from always having access :)

2019-08-19 16:46 UTC, SpartakusMd commented on src/Controller/ActivityController.php
> +            ->setFrom($_ENV['EMAIL_FROM'])
Inject the parameter `EMAIL_FROM` and make this change everywhere.

2019-08-19 16:46 UTC, SpartakusMd commented on src/Controller/ActivityController.php
> +                    'mail/mail_for_PM.html.twig',
`mail_for_PM` doesn't indicate what mail is this. Is it that a user has been assigned to the PM, is it a new job to validate e.t.c.

2019-08-19 16:46 UTC, SpartakusMd commented on src/Controller/ActivityController.php
> +        $message = (new Swift_Message(
Create a separate service for sending emails.

2019-08-19 16:46 UTC, SpartakusMd commented on src/Repository/ActivityRepository.php
> +        $hasAccess = $this->checker->isGranted('ROLE_ADMIN');
Everywhere the variable name is `$hasAccess`! Why not use something more explicit like `$isAdmin`.

2019-08-19 16:46 UTC, SpartakusMd commented on src/Transformer/ActivityTransformer.php
> +        if ($activity->getStatus() !== Activity::STATUS_IN_VALIDATION) {
👍 Very good :)

2019-08-21 09:34 UTC, SpartakusMd requested changes

2019-08-21 09:34 UTC, SpartakusMd commented on src/Service/EmailSender.php
> +    use ControllerTrait;
ControllerTrait should be used only in Controllers.

2019-08-21 11:44 UTC, merged