[BE] Validate a job
p5chi-auf/PentaBee-api pull request #87
Opened 2019-08-21 12:13 UTC by nspc97

[BE] Validate a job
https://trello.com/c/du6VOqEr/101-be-validate-a-job

2019-08-21 12:18 UTC, MihaiDruta commented on src/Controller/ActivityController.php
> +     * Validate an applicant.
Should be: validate a Job

2019-08-21 12:20 UTC, MihaiDruta approved these changes

2019-08-21 12:24 UTC, SpartakusMd approved these changes

2019-08-21 12:25 UTC, SpartakusMd requested changes
Add tests for validation:
- Successful test
- one test per each failing case

2019-08-23 10:46 UTC, SpartakusMd requested changes

2019-08-23 10:46 UTC, SpartakusMd commented on src/DataFixtures/UserFixtures.php
> +            $userRepository->unassignProjectManager($user);
Why are you doing this in fixtures? Everything from database is removed at each load of fixtures.

2019-08-23 10:51 UTC, SpartakusMd commented
Travis build is failing. Check why and fix the issue.

2019-08-28 07:29 UTC, SpartakusMd approved these changes

2019-08-28 07:29 UTC, merged