[BE] Test cases for login
p5chi-auf/PentaBee-api pull request #88
Opened 2019-08-21 12:27 UTC by MihaiDruta

[BE] Test cases for login
https://trello.com/c/RsPpY9pu/107-be-test-cases-for-login

Added test cases for login

2019-08-26 12:42 UTC, nspc97 approved these changes

2019-08-28 09:50 UTC, SpartakusMd requested changes
Travis is still failing.

2019-08-28 09:50 UTC, SpartakusMd commented on .env.test
> +###< lexik/jwt-authentication-bundle ###
Leave an empty line at the end.

2019-08-28 09:50 UTC, SpartakusMd commented on src/DataFixtures/TypeFixtures.php
>          'dt estimation',
Make the words capitalized where needed. The shouldn't be all lowercase.

2019-08-28 09:50 UTC, SpartakusMd commented on tests/LoginTest.php
> +        $decodedToken = $this->tokenDecode($token);
Use `Lexik\Bundle\JWTAuthenticationBundle\Encoder\JWTEncoderInterface::decode()`

2019-08-28 13:14 UTC, SpartakusMd requested changes

2019-08-28 13:14 UTC, SpartakusMd commented on src/DataFixtures/ActivityFixtures.php
> +            $type = $this->getReference('type_' . TypeFixtures::TYPES[rand(0, 8)]);
8 will be undefined. The count starts from 0 not 1.

2019-08-29 08:15 UTC, merged