[BE] Decline job validation
p5chi-auf/PentaBee-api pull request #89
Opened 2019-08-28 11:51 UTC by nspc97

[BE] Decline job validation
https://trello.com/c/FU9eHY3Y/102-be-decline-job-validation

2019-08-28 11:54 UTC, MihaiDruta approved these changes

2019-08-28 14:12 UTC, SpartakusMd commented
Add tests for:

1. Successful reject
2. Unsuccessful reject
3. Get list of jobs
    - check that current user sees his rejected job
    - current user cannot see other users rejected job
    - admin can see all rejected jobs

2019-08-29 12:11 UTC, SpartakusMd requested changes

2019-08-29 12:11 UTC, SpartakusMd commented on tests/RejectJobTest.php
> +        $activityRepository = $this->getRepository($kernel, Activity::class);
`activityRepository  = self::$container->get(Activity::class);`

2019-08-29 13:17 UTC, merged